### ISSUE TITLE
Owner can bypass the restriction of address(0) and can assign owner as address(0) to contract. (business logic bug)

### ISSUE THREAD

**Issue by newfolderj** [AelinXYZ/aelin#163]
Hey Aelin team,

I hope you are fine and doing good, I have been reading your contracts since I started looking at your audits done by different individuals and companies, many things are being pointed out by the auditors. However, one **Medium BUG** I would like to address here at https://github.com/AelinXYZ/aelin/blob/53710152d3746cbfc5337e88a3f01694d5b26999/contracts/Owned.sol.

### BUG:

The contract work as expected as at the start it checks for `address(0)`, owner can never be address(0) fair enough. However, this restriction is lacking when changing the owner functionality comes in at `nominateNewOwner`.

In order to test it, try to deploy the contract with address(0) which would revert due to ` require(_owner != address(0), "Owner address cannot be 0");`, now deploy the contract normally and pass `address(0)` at `nominateNewOwner` function. This makes the possibility of making invalid address the owner of the contract.

### Possible Recommendation:

add check at address(0) as:
```
function nominateNewOwner(address _owner) external onlyOwner {
        require(_owner != address(0), "No zero address");
        nominatedOwner = _owner;
        emit OwnerNominated(_owner);
    }
```

Thank you,

Regards,
newfolder

**Comment by 0xcdb** [comment]
Hey, not an issue as if `address(0)` is passed by mistake in `nominateNewOwner()` Owner can just remake a transaction with the correct address this time.
Also please note that none of the contracts using `Owned.sol` are being used anymore and that this contract has been deprecated on `dev`.
